bezkoder:
    app:
        jwtExpirationMs: 86400000
        jwtSecret: bezKoderSecretKey
spring:
    data:
        mongodb:
            database: bezkoder_db
            host: localhost
            port: 27017
server:
    port : 8080